//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutImage
    {
        public int Id { get; set; }
        public string ImageName { get; set; }
        public bool ImageStatus { get; set; }
    }
}
