//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int Id { get; set; }
        public string ExperienceTwoTitle { get; set; }
        public string ExperienceDescription { get; set; }
        public string ExperienceDate { get; set; }
        public string ExperienceName { get; set; }
        public string ExperienceLinks { get; set; }
        public string Image { get; set; }
    }
}
